Sw 155 feedback for elbow sensor
Capstone-Projects-2024-Spring/project-smartweights pull request #132
Opened 2024-04-14 18:34 UTC by SlowMiata

created all the thresholds for each of the possible movements dumbbell and elbow
created a function to get the overall form for the workout
implemented the elbow feedback for every set
created dangerous form function (need to implement somehow still)

2024-04-14 20:25 UTC, DanielEap requested changes
Just change back SmartWeightsApp.swift to load the loginPage() 

Otherwise, everything looks great, remind us to have you demo this!

2024-04-15 13:48 UTC, AdamRa97 requested changes
once the changes are made i think it lgtm

2024-04-15 13:48 UTC, AdamRa97 commented on SmartWeights/SmartWeights/SmartWeightsApp.swift
> +            //bleView(ble: BLEcentral())
change this back to `LoginView()`

2024-04-16 16:00 UTC, SlowMiata commented
PLEASE DONT MERGE THIS PULL REQUEST YET

2024-04-16 21:22 UTC, closed without merging