Sw 175 inventory and shop connectivity for backgrounds clothes pets
Capstone-Projects-2024-Spring/project-smartweights pull request #134
Opened 2024-04-14 20:17 UTC by DanielEap

purchases show up in customize, fetches user's current inventory

2024-04-14 20:36 UTC, SlowMiata requested changes
you could add conditional so that they can't say any voice commands at any time.
I.E. they can only say finish if they are mid workout or next if the workout is currently paused

2024-04-14 20:41 UTC, DanielEap commented
> you could add conditional so that they can't say any voice commands at any time. I.E. they can only say finish if they are mid workout or next if the workout is currently paused

was this meant for the other Pull request?

2024-04-15 13:49 UTC, jtstanczak7 approved these changes

2024-04-15 13:49 UTC, SlowMiata approved these changes

2024-04-16 15:21 UTC, merged